# Generated by Django 3.2.2 on 2021-05-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='local_number',
            field=models.CharField(max_length=16),
        ),
    ]
